/*
 * generated by Xtext 2.22.0
 */
package org.xtext.wesnoth;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class WailRuntimeModule extends AbstractWailRuntimeModule {
}
