/**
 * generated by Xtext 2.22.0
 */
package org.xtext.wesnoth.wail;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Baseline</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.wesnoth.wail.Baseline#getAlways <em>Always</em>}</li>
 * </ul>
 *
 * @see org.xtext.wesnoth.wail.WailPackage#getBaseline()
 * @model
 * @generated
 */
public interface Baseline extends whenRules
{
  /**
   * Returns the value of the '<em><b>Always</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Always</em>' attribute.
   * @see #setAlways(String)
   * @see org.xtext.wesnoth.wail.WailPackage#getBaseline_Always()
   * @model
   * @generated
   */
  String getAlways();

  /**
   * Sets the value of the '{@link org.xtext.wesnoth.wail.Baseline#getAlways <em>Always</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Always</em>' attribute.
   * @see #getAlways()
   * @generated
   */
  void setAlways(String value);

} // Baseline
