/**
 * generated by Xtext 2.22.0
 */
package org.xtext.wesnoth.wail;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Caution</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.wesnoth.wail.Caution#getCautionval <em>Cautionval</em>}</li>
 * </ul>
 *
 * @see org.xtext.wesnoth.wail.WailPackage#getCaution()
 * @model
 * @generated
 */
public interface Caution extends EObject
{
  /**
   * Returns the value of the '<em><b>Cautionval</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cautionval</em>' attribute.
   * @see #setCautionval(String)
   * @see org.xtext.wesnoth.wail.WailPackage#getCaution_Cautionval()
   * @model
   * @generated
   */
  String getCautionval();

  /**
   * Sets the value of the '{@link org.xtext.wesnoth.wail.Caution#getCautionval <em>Cautionval</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cautionval</em>' attribute.
   * @see #getCautionval()
   * @generated
   */
  void setCautionval(String value);

} // Caution
