/**
 * generated by Xtext 2.22.0
 */
package org.xtext.wesnoth.wail;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Damage</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.wesnoth.wail.Damage#getHealth <em>Health</em>}</li>
 * </ul>
 *
 * @see org.xtext.wesnoth.wail.WailPackage#getDamage()
 * @model
 * @generated
 */
public interface Damage extends whenRules
{
  /**
   * Returns the value of the '<em><b>Health</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Health</em>' attribute.
   * @see #setHealth(int)
   * @see org.xtext.wesnoth.wail.WailPackage#getDamage_Health()
   * @model
   * @generated
   */
  int getHealth();

  /**
   * Sets the value of the '{@link org.xtext.wesnoth.wail.Damage#getHealth <em>Health</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Health</em>' attribute.
   * @see #getHealth()
   * @generated
   */
  void setHealth(int value);

} // Damage
