/**
 * generated by Xtext 2.22.0
 */
package org.xtext.wesnoth.wail;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Fragment</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.wesnoth.wail.Fragment#getCondition <em>Condition</em>}</li>
 *   <li>{@link org.xtext.wesnoth.wail.Fragment#getDefualt_cas <em>Defualt cas</em>}</li>
 * </ul>
 *
 * @see org.xtext.wesnoth.wail.WailPackage#getFragment()
 * @model
 * @generated
 */
public interface Fragment extends EObject
{
  /**
   * Returns the value of the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' containment reference.
   * @see #setCondition(Conditional)
   * @see org.xtext.wesnoth.wail.WailPackage#getFragment_Condition()
   * @model containment="true"
   * @generated
   */
  Conditional getCondition();

  /**
   * Sets the value of the '{@link org.xtext.wesnoth.wail.Fragment#getCondition <em>Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' containment reference.
   * @see #getCondition()
   * @generated
   */
  void setCondition(Conditional value);

  /**
   * Returns the value of the '<em><b>Defualt cas</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.wesnoth.wail.Defualt_CA}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Defualt cas</em>' containment reference list.
   * @see org.xtext.wesnoth.wail.WailPackage#getFragment_Defualt_cas()
   * @model containment="true"
   * @generated
   */
  EList<Defualt_CA> getDefualt_cas();

} // Fragment
