/**
 * generated by Xtext 2.22.0
 */
package org.xtext.wesnoth.wail;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Grouping</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.wesnoth.wail.Grouping#getGroupingVal <em>Grouping Val</em>}</li>
 * </ul>
 *
 * @see org.xtext.wesnoth.wail.WailPackage#getGrouping()
 * @model
 * @generated
 */
public interface Grouping extends EObject
{
  /**
   * Returns the value of the '<em><b>Grouping Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Grouping Val</em>' attribute.
   * @see #setGroupingVal(String)
   * @see org.xtext.wesnoth.wail.WailPackage#getGrouping_GroupingVal()
   * @model
   * @generated
   */
  String getGroupingVal();

  /**
   * Sets the value of the '{@link org.xtext.wesnoth.wail.Grouping#getGroupingVal <em>Grouping Val</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Grouping Val</em>' attribute.
   * @see #getGroupingVal()
   * @generated
   */
  void setGroupingVal(String value);

} // Grouping
