/**
 * generated by Xtext 2.22.0
 */
package org.xtext.wesnoth.wail;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Unit Equals</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.wesnoth.wail.UnitEquals#getUnit <em>Unit</em>}</li>
 * </ul>
 *
 * @see org.xtext.wesnoth.wail.WailPackage#getUnitEquals()
 * @model
 * @generated
 */
public interface UnitEquals extends whenRules
{
  /**
   * Returns the value of the '<em><b>Unit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unit</em>' attribute.
   * @see #setUnit(String)
   * @see org.xtext.wesnoth.wail.WailPackage#getUnitEquals_Unit()
   * @model
   * @generated
   */
  String getUnit();

  /**
   * Sets the value of the '{@link org.xtext.wesnoth.wail.UnitEquals#getUnit <em>Unit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unit</em>' attribute.
   * @see #getUnit()
   * @generated
   */
  void setUnit(String value);

} // UnitEquals
