/**
 * generated by Xtext 2.22.0
 */
package org.xtext.wesnoth.wail;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.wesnoth.wail.WailFactory
 * @model kind="package"
 * @generated
 */
public interface WailPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "wail";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/wesnoth/Wail";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "wail";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  WailPackage eINSTANCE = org.xtext.wesnoth.wail.impl.WailPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.wesnoth.wail.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.wesnoth.wail.impl.ModelImpl
   * @see org.xtext.wesnoth.wail.impl.WailPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.wesnoth.wail.impl.RuleImpl <em>Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.wesnoth.wail.impl.RuleImpl
   * @see org.xtext.wesnoth.wail.impl.WailPackageImpl#getRule()
   * @generated
   */
  int RULE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__NAME = 0;

  /**
   * The feature id for the '<em><b>Fragments</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__FRAGMENTS = 1;

  /**
   * The feature id for the '<em><b>Goals</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__GOALS = 2;

  /**
   * The feature id for the '<em><b>Aggressionval</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__AGGRESSIONVAL = 3;

  /**
   * The feature id for the '<em><b>Cautionval</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__CAUTIONVAL = 4;

  /**
   * The feature id for the '<em><b>Grouping Val</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__GROUPING_VAL = 5;

  /**
   * The feature id for the '<em><b>Units</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__UNITS = 6;

  /**
   * The number of structural features of the '<em>Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_FEATURE_COUNT = 7;

  /**
   * The meta object id for the '{@link org.xtext.wesnoth.wail.impl.GroupingImpl <em>Grouping</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.wesnoth.wail.impl.GroupingImpl
   * @see org.xtext.wesnoth.wail.impl.WailPackageImpl#getGrouping()
   * @generated
   */
  int GROUPING = 2;

  /**
   * The feature id for the '<em><b>Grouping Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GROUPING__GROUPING_VAL = 0;

  /**
   * The number of structural features of the '<em>Grouping</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GROUPING_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.wesnoth.wail.impl.FragmentImpl <em>Fragment</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.wesnoth.wail.impl.FragmentImpl
   * @see org.xtext.wesnoth.wail.impl.WailPackageImpl#getFragment()
   * @generated
   */
  int FRAGMENT = 3;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FRAGMENT__CONDITION = 0;

  /**
   * The feature id for the '<em><b>Defualt cas</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FRAGMENT__DEFUALT_CAS = 1;

  /**
   * The number of structural features of the '<em>Fragment</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FRAGMENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.wesnoth.wail.impl.ConditionalImpl <em>Conditional</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.wesnoth.wail.impl.ConditionalImpl
   * @see org.xtext.wesnoth.wail.impl.WailPackageImpl#getConditional()
   * @generated
   */
  int CONDITIONAL = 4;

  /**
   * The feature id for the '<em><b>X</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONAL__X = 0;

  /**
   * The number of structural features of the '<em>Conditional</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONAL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.wesnoth.wail.impl.RecruitmentImpl <em>Recruitment</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.wesnoth.wail.impl.RecruitmentImpl
   * @see org.xtext.wesnoth.wail.impl.WailPackageImpl#getRecruitment()
   * @generated
   */
  int RECRUITMENT = 5;

  /**
   * The feature id for the '<em><b>Unitslist</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECRUITMENT__UNITSLIST = 0;

  /**
   * The feature id for the '<em><b>Turns</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECRUITMENT__TURNS = 1;

  /**
   * The feature id for the '<em><b>Importance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECRUITMENT__IMPORTANCE = 2;

  /**
   * The feature id for the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECRUITMENT__NUMBER = 3;

  /**
   * The number of structural features of the '<em>Recruitment</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECRUITMENT_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.wesnoth.wail.impl.whenRulesImpl <em>when Rules</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.wesnoth.wail.impl.whenRulesImpl
   * @see org.xtext.wesnoth.wail.impl.WailPackageImpl#getwhenRules()
   * @generated
   */
  int WHEN_RULES = 6;

  /**
   * The number of structural features of the '<em>when Rules</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHEN_RULES_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.wesnoth.wail.impl.IDEqualsImpl <em>ID Equals</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.wesnoth.wail.impl.IDEqualsImpl
   * @see org.xtext.wesnoth.wail.impl.WailPackageImpl#getIDEquals()
   * @generated
   */
  int ID_EQUALS = 7;

  /**
   * The feature id for the '<em><b>Unit ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ID_EQUALS__UNIT_ID = WHEN_RULES_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>ID Equals</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ID_EQUALS_FEATURE_COUNT = WHEN_RULES_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.wesnoth.wail.impl.BaselineImpl <em>Baseline</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.wesnoth.wail.impl.BaselineImpl
   * @see org.xtext.wesnoth.wail.impl.WailPackageImpl#getBaseline()
   * @generated
   */
  int BASELINE = 8;

  /**
   * The feature id for the '<em><b>Always</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BASELINE__ALWAYS = WHEN_RULES_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Baseline</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BASELINE_FEATURE_COUNT = WHEN_RULES_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.wesnoth.wail.impl.DamageImpl <em>Damage</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.wesnoth.wail.impl.DamageImpl
   * @see org.xtext.wesnoth.wail.impl.WailPackageImpl#getDamage()
   * @generated
   */
  int DAMAGE = 9;

  /**
   * The feature id for the '<em><b>Health</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DAMAGE__HEALTH = WHEN_RULES_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Damage</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DAMAGE_FEATURE_COUNT = WHEN_RULES_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.wesnoth.wail.impl.AtLocationImpl <em>At Location</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.wesnoth.wail.impl.AtLocationImpl
   * @see org.xtext.wesnoth.wail.impl.WailPackageImpl#getAtLocation()
   * @generated
   */
  int AT_LOCATION = 10;

  /**
   * The feature id for the '<em><b>XAxis</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AT_LOCATION__XAXIS = WHEN_RULES_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>YAxis</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AT_LOCATION__YAXIS = WHEN_RULES_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>At Location</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AT_LOCATION_FEATURE_COUNT = WHEN_RULES_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.wesnoth.wail.impl.UnitEqualsImpl <em>Unit Equals</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.wesnoth.wail.impl.UnitEqualsImpl
   * @see org.xtext.wesnoth.wail.impl.WailPackageImpl#getUnitEquals()
   * @generated
   */
  int UNIT_EQUALS = 11;

  /**
   * The feature id for the '<em><b>Unit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNIT_EQUALS__UNIT = WHEN_RULES_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Unit Equals</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNIT_EQUALS_FEATURE_COUNT = WHEN_RULES_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.wesnoth.wail.impl.GoalImpl <em>Goal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.wesnoth.wail.impl.GoalImpl
   * @see org.xtext.wesnoth.wail.impl.WailPackageImpl#getGoal()
   * @generated
   */
  int GOAL = 12;

  /**
   * The feature id for the '<em><b>Goal</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOAL__GOAL = 0;

  /**
   * The number of structural features of the '<em>Goal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOAL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.wesnoth.wail.impl.ProtectLeaderImpl <em>Protect Leader</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.wesnoth.wail.impl.ProtectLeaderImpl
   * @see org.xtext.wesnoth.wail.impl.WailPackageImpl#getProtectLeader()
   * @generated
   */
  int PROTECT_LEADER = 13;

  /**
   * The feature id for the '<em><b>Goal</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROTECT_LEADER__GOAL = GOAL__GOAL;

  /**
   * The feature id for the '<em><b>Location Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROTECT_LEADER__LOCATION_VALUE = GOAL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Protection Radius</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROTECT_LEADER__PROTECTION_RADIUS = GOAL_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Proc Side</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROTECT_LEADER__PROC_SIDE = GOAL_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Protect Leader</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROTECT_LEADER_FEATURE_COUNT = GOAL_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.wesnoth.wail.impl.ProtectUnitIDImpl <em>Protect Unit ID</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.wesnoth.wail.impl.ProtectUnitIDImpl
   * @see org.xtext.wesnoth.wail.impl.WailPackageImpl#getProtectUnitID()
   * @generated
   */
  int PROTECT_UNIT_ID = 14;

  /**
   * The feature id for the '<em><b>Goal</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROTECT_UNIT_ID__GOAL = GOAL__GOAL;

  /**
   * The feature id for the '<em><b>Location Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROTECT_UNIT_ID__LOCATION_VALUE = GOAL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Protection Radius</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROTECT_UNIT_ID__PROTECTION_RADIUS = GOAL_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Proc Side</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROTECT_UNIT_ID__PROC_SIDE = GOAL_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Proc ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROTECT_UNIT_ID__PROC_ID = GOAL_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Protect Unit ID</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROTECT_UNIT_ID_FEATURE_COUNT = GOAL_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.xtext.wesnoth.wail.impl.ProtectUnitTypeImpl <em>Protect Unit Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.wesnoth.wail.impl.ProtectUnitTypeImpl
   * @see org.xtext.wesnoth.wail.impl.WailPackageImpl#getProtectUnitType()
   * @generated
   */
  int PROTECT_UNIT_TYPE = 15;

  /**
   * The feature id for the '<em><b>Goal</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROTECT_UNIT_TYPE__GOAL = GOAL__GOAL;

  /**
   * The feature id for the '<em><b>Location Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROTECT_UNIT_TYPE__LOCATION_VALUE = GOAL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Protection Radius</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROTECT_UNIT_TYPE__PROTECTION_RADIUS = GOAL_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Proc Side</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROTECT_UNIT_TYPE__PROC_SIDE = GOAL_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Proc Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROTECT_UNIT_TYPE__PROC_TYPE = GOAL_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Protect Unit Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROTECT_UNIT_TYPE_FEATURE_COUNT = GOAL_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.xtext.wesnoth.wail.impl.ProtectLocationImpl <em>Protect Location</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.wesnoth.wail.impl.ProtectLocationImpl
   * @see org.xtext.wesnoth.wail.impl.WailPackageImpl#getProtectLocation()
   * @generated
   */
  int PROTECT_LOCATION = 16;

  /**
   * The feature id for the '<em><b>Goal</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROTECT_LOCATION__GOAL = GOAL__GOAL;

  /**
   * The feature id for the '<em><b>XAxis</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROTECT_LOCATION__XAXIS = GOAL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>YAxis</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROTECT_LOCATION__YAXIS = GOAL_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Loc Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROTECT_LOCATION__LOC_VALUE = GOAL_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Proc Rad</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROTECT_LOCATION__PROC_RAD = GOAL_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Protect Location</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROTECT_LOCATION_FEATURE_COUNT = GOAL_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.xtext.wesnoth.wail.impl.GoaLocationImpl <em>Goa Location</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.wesnoth.wail.impl.GoaLocationImpl
   * @see org.xtext.wesnoth.wail.impl.WailPackageImpl#getGoaLocation()
   * @generated
   */
  int GOA_LOCATION = 17;

  /**
   * The feature id for the '<em><b>XAxis</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOA_LOCATION__XAXIS = 0;

  /**
   * The feature id for the '<em><b>YAxis</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOA_LOCATION__YAXIS = 1;

  /**
   * The feature id for the '<em><b>Loc Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOA_LOCATION__LOC_VALUE = 2;

  /**
   * The number of structural features of the '<em>Goa Location</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOA_LOCATION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.wesnoth.wail.impl.AggressionImpl <em>Aggression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.wesnoth.wail.impl.AggressionImpl
   * @see org.xtext.wesnoth.wail.impl.WailPackageImpl#getAggression()
   * @generated
   */
  int AGGRESSION = 18;

  /**
   * The feature id for the '<em><b>Aggression Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AGGRESSION__AGGRESSION_VAL = 0;

  /**
   * The number of structural features of the '<em>Aggression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AGGRESSION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.wesnoth.wail.impl.CautionImpl <em>Caution</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.wesnoth.wail.impl.CautionImpl
   * @see org.xtext.wesnoth.wail.impl.WailPackageImpl#getCaution()
   * @generated
   */
  int CAUTION = 19;

  /**
   * The feature id for the '<em><b>Cautionval</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAUTION__CAUTIONVAL = 0;

  /**
   * The number of structural features of the '<em>Caution</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAUTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.wesnoth.wail.impl.Defualt_CAImpl <em>Defualt CA</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.wesnoth.wail.impl.Defualt_CAImpl
   * @see org.xtext.wesnoth.wail.impl.WailPackageImpl#getDefualt_CA()
   * @generated
   */
  int DEFUALT_CA = 20;

  /**
   * The feature id for the '<em><b>Ca Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFUALT_CA__CA_TYPE = 0;

  /**
   * The feature id for the '<em><b>Cost</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFUALT_CA__COST = 1;

  /**
   * The number of structural features of the '<em>Defualt CA</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFUALT_CA_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link org.xtext.wesnoth.wail.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.wesnoth.wail.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.wesnoth.wail.Model#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.xtext.wesnoth.wail.Model#getElements()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Elements();

  /**
   * Returns the meta object for class '{@link org.xtext.wesnoth.wail.Rule <em>Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule</em>'.
   * @see org.xtext.wesnoth.wail.Rule
   * @generated
   */
  EClass getRule();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.wesnoth.wail.Rule#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.wesnoth.wail.Rule#getName()
   * @see #getRule()
   * @generated
   */
  EAttribute getRule_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.wesnoth.wail.Rule#getFragments <em>Fragments</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Fragments</em>'.
   * @see org.xtext.wesnoth.wail.Rule#getFragments()
   * @see #getRule()
   * @generated
   */
  EReference getRule_Fragments();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.wesnoth.wail.Rule#getGoals <em>Goals</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Goals</em>'.
   * @see org.xtext.wesnoth.wail.Rule#getGoals()
   * @see #getRule()
   * @generated
   */
  EReference getRule_Goals();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.wesnoth.wail.Rule#getAggressionval <em>Aggressionval</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Aggressionval</em>'.
   * @see org.xtext.wesnoth.wail.Rule#getAggressionval()
   * @see #getRule()
   * @generated
   */
  EReference getRule_Aggressionval();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.wesnoth.wail.Rule#getCautionval <em>Cautionval</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cautionval</em>'.
   * @see org.xtext.wesnoth.wail.Rule#getCautionval()
   * @see #getRule()
   * @generated
   */
  EReference getRule_Cautionval();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.wesnoth.wail.Rule#getGroupingVal <em>Grouping Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Grouping Val</em>'.
   * @see org.xtext.wesnoth.wail.Rule#getGroupingVal()
   * @see #getRule()
   * @generated
   */
  EReference getRule_GroupingVal();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.wesnoth.wail.Rule#getUnits <em>Units</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Units</em>'.
   * @see org.xtext.wesnoth.wail.Rule#getUnits()
   * @see #getRule()
   * @generated
   */
  EReference getRule_Units();

  /**
   * Returns the meta object for class '{@link org.xtext.wesnoth.wail.Grouping <em>Grouping</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Grouping</em>'.
   * @see org.xtext.wesnoth.wail.Grouping
   * @generated
   */
  EClass getGrouping();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.wesnoth.wail.Grouping#getGroupingVal <em>Grouping Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Grouping Val</em>'.
   * @see org.xtext.wesnoth.wail.Grouping#getGroupingVal()
   * @see #getGrouping()
   * @generated
   */
  EAttribute getGrouping_GroupingVal();

  /**
   * Returns the meta object for class '{@link org.xtext.wesnoth.wail.Fragment <em>Fragment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fragment</em>'.
   * @see org.xtext.wesnoth.wail.Fragment
   * @generated
   */
  EClass getFragment();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.wesnoth.wail.Fragment#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see org.xtext.wesnoth.wail.Fragment#getCondition()
   * @see #getFragment()
   * @generated
   */
  EReference getFragment_Condition();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.wesnoth.wail.Fragment#getDefualt_cas <em>Defualt cas</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Defualt cas</em>'.
   * @see org.xtext.wesnoth.wail.Fragment#getDefualt_cas()
   * @see #getFragment()
   * @generated
   */
  EReference getFragment_Defualt_cas();

  /**
   * Returns the meta object for class '{@link org.xtext.wesnoth.wail.Conditional <em>Conditional</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Conditional</em>'.
   * @see org.xtext.wesnoth.wail.Conditional
   * @generated
   */
  EClass getConditional();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.wesnoth.wail.Conditional#getX <em>X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>X</em>'.
   * @see org.xtext.wesnoth.wail.Conditional#getX()
   * @see #getConditional()
   * @generated
   */
  EReference getConditional_X();

  /**
   * Returns the meta object for class '{@link org.xtext.wesnoth.wail.Recruitment <em>Recruitment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Recruitment</em>'.
   * @see org.xtext.wesnoth.wail.Recruitment
   * @generated
   */
  EClass getRecruitment();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.wesnoth.wail.Recruitment#getUnitslist <em>Unitslist</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Unitslist</em>'.
   * @see org.xtext.wesnoth.wail.Recruitment#getUnitslist()
   * @see #getRecruitment()
   * @generated
   */
  EAttribute getRecruitment_Unitslist();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.wesnoth.wail.Recruitment#getTurns <em>Turns</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Turns</em>'.
   * @see org.xtext.wesnoth.wail.Recruitment#getTurns()
   * @see #getRecruitment()
   * @generated
   */
  EAttribute getRecruitment_Turns();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.wesnoth.wail.Recruitment#getImportance <em>Importance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Importance</em>'.
   * @see org.xtext.wesnoth.wail.Recruitment#getImportance()
   * @see #getRecruitment()
   * @generated
   */
  EAttribute getRecruitment_Importance();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.wesnoth.wail.Recruitment#getNumber <em>Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Number</em>'.
   * @see org.xtext.wesnoth.wail.Recruitment#getNumber()
   * @see #getRecruitment()
   * @generated
   */
  EAttribute getRecruitment_Number();

  /**
   * Returns the meta object for class '{@link org.xtext.wesnoth.wail.whenRules <em>when Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>when Rules</em>'.
   * @see org.xtext.wesnoth.wail.whenRules
   * @generated
   */
  EClass getwhenRules();

  /**
   * Returns the meta object for class '{@link org.xtext.wesnoth.wail.IDEquals <em>ID Equals</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>ID Equals</em>'.
   * @see org.xtext.wesnoth.wail.IDEquals
   * @generated
   */
  EClass getIDEquals();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.wesnoth.wail.IDEquals#getUnitID <em>Unit ID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Unit ID</em>'.
   * @see org.xtext.wesnoth.wail.IDEquals#getUnitID()
   * @see #getIDEquals()
   * @generated
   */
  EAttribute getIDEquals_UnitID();

  /**
   * Returns the meta object for class '{@link org.xtext.wesnoth.wail.Baseline <em>Baseline</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Baseline</em>'.
   * @see org.xtext.wesnoth.wail.Baseline
   * @generated
   */
  EClass getBaseline();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.wesnoth.wail.Baseline#getAlways <em>Always</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Always</em>'.
   * @see org.xtext.wesnoth.wail.Baseline#getAlways()
   * @see #getBaseline()
   * @generated
   */
  EAttribute getBaseline_Always();

  /**
   * Returns the meta object for class '{@link org.xtext.wesnoth.wail.Damage <em>Damage</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Damage</em>'.
   * @see org.xtext.wesnoth.wail.Damage
   * @generated
   */
  EClass getDamage();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.wesnoth.wail.Damage#getHealth <em>Health</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Health</em>'.
   * @see org.xtext.wesnoth.wail.Damage#getHealth()
   * @see #getDamage()
   * @generated
   */
  EAttribute getDamage_Health();

  /**
   * Returns the meta object for class '{@link org.xtext.wesnoth.wail.AtLocation <em>At Location</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>At Location</em>'.
   * @see org.xtext.wesnoth.wail.AtLocation
   * @generated
   */
  EClass getAtLocation();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.wesnoth.wail.AtLocation#getXAxis <em>XAxis</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>XAxis</em>'.
   * @see org.xtext.wesnoth.wail.AtLocation#getXAxis()
   * @see #getAtLocation()
   * @generated
   */
  EAttribute getAtLocation_XAxis();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.wesnoth.wail.AtLocation#getYAxis <em>YAxis</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>YAxis</em>'.
   * @see org.xtext.wesnoth.wail.AtLocation#getYAxis()
   * @see #getAtLocation()
   * @generated
   */
  EAttribute getAtLocation_YAxis();

  /**
   * Returns the meta object for class '{@link org.xtext.wesnoth.wail.UnitEquals <em>Unit Equals</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Unit Equals</em>'.
   * @see org.xtext.wesnoth.wail.UnitEquals
   * @generated
   */
  EClass getUnitEquals();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.wesnoth.wail.UnitEquals#getUnit <em>Unit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Unit</em>'.
   * @see org.xtext.wesnoth.wail.UnitEquals#getUnit()
   * @see #getUnitEquals()
   * @generated
   */
  EAttribute getUnitEquals_Unit();

  /**
   * Returns the meta object for class '{@link org.xtext.wesnoth.wail.Goal <em>Goal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Goal</em>'.
   * @see org.xtext.wesnoth.wail.Goal
   * @generated
   */
  EClass getGoal();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.wesnoth.wail.Goal#getGoal <em>Goal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Goal</em>'.
   * @see org.xtext.wesnoth.wail.Goal#getGoal()
   * @see #getGoal()
   * @generated
   */
  EReference getGoal_Goal();

  /**
   * Returns the meta object for class '{@link org.xtext.wesnoth.wail.ProtectLeader <em>Protect Leader</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Protect Leader</em>'.
   * @see org.xtext.wesnoth.wail.ProtectLeader
   * @generated
   */
  EClass getProtectLeader();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.wesnoth.wail.ProtectLeader#getLocationValue <em>Location Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Location Value</em>'.
   * @see org.xtext.wesnoth.wail.ProtectLeader#getLocationValue()
   * @see #getProtectLeader()
   * @generated
   */
  EAttribute getProtectLeader_LocationValue();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.wesnoth.wail.ProtectLeader#getProtectionRadius <em>Protection Radius</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Protection Radius</em>'.
   * @see org.xtext.wesnoth.wail.ProtectLeader#getProtectionRadius()
   * @see #getProtectLeader()
   * @generated
   */
  EAttribute getProtectLeader_ProtectionRadius();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.wesnoth.wail.ProtectLeader#getProcSide <em>Proc Side</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Proc Side</em>'.
   * @see org.xtext.wesnoth.wail.ProtectLeader#getProcSide()
   * @see #getProtectLeader()
   * @generated
   */
  EAttribute getProtectLeader_ProcSide();

  /**
   * Returns the meta object for class '{@link org.xtext.wesnoth.wail.ProtectUnitID <em>Protect Unit ID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Protect Unit ID</em>'.
   * @see org.xtext.wesnoth.wail.ProtectUnitID
   * @generated
   */
  EClass getProtectUnitID();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.wesnoth.wail.ProtectUnitID#getLocationValue <em>Location Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Location Value</em>'.
   * @see org.xtext.wesnoth.wail.ProtectUnitID#getLocationValue()
   * @see #getProtectUnitID()
   * @generated
   */
  EAttribute getProtectUnitID_LocationValue();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.wesnoth.wail.ProtectUnitID#getProtectionRadius <em>Protection Radius</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Protection Radius</em>'.
   * @see org.xtext.wesnoth.wail.ProtectUnitID#getProtectionRadius()
   * @see #getProtectUnitID()
   * @generated
   */
  EAttribute getProtectUnitID_ProtectionRadius();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.wesnoth.wail.ProtectUnitID#getProcSide <em>Proc Side</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Proc Side</em>'.
   * @see org.xtext.wesnoth.wail.ProtectUnitID#getProcSide()
   * @see #getProtectUnitID()
   * @generated
   */
  EAttribute getProtectUnitID_ProcSide();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.wesnoth.wail.ProtectUnitID#getProcID <em>Proc ID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Proc ID</em>'.
   * @see org.xtext.wesnoth.wail.ProtectUnitID#getProcID()
   * @see #getProtectUnitID()
   * @generated
   */
  EAttribute getProtectUnitID_ProcID();

  /**
   * Returns the meta object for class '{@link org.xtext.wesnoth.wail.ProtectUnitType <em>Protect Unit Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Protect Unit Type</em>'.
   * @see org.xtext.wesnoth.wail.ProtectUnitType
   * @generated
   */
  EClass getProtectUnitType();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.wesnoth.wail.ProtectUnitType#getLocationValue <em>Location Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Location Value</em>'.
   * @see org.xtext.wesnoth.wail.ProtectUnitType#getLocationValue()
   * @see #getProtectUnitType()
   * @generated
   */
  EAttribute getProtectUnitType_LocationValue();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.wesnoth.wail.ProtectUnitType#getProtectionRadius <em>Protection Radius</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Protection Radius</em>'.
   * @see org.xtext.wesnoth.wail.ProtectUnitType#getProtectionRadius()
   * @see #getProtectUnitType()
   * @generated
   */
  EAttribute getProtectUnitType_ProtectionRadius();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.wesnoth.wail.ProtectUnitType#getProcSide <em>Proc Side</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Proc Side</em>'.
   * @see org.xtext.wesnoth.wail.ProtectUnitType#getProcSide()
   * @see #getProtectUnitType()
   * @generated
   */
  EAttribute getProtectUnitType_ProcSide();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.wesnoth.wail.ProtectUnitType#getProcType <em>Proc Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Proc Type</em>'.
   * @see org.xtext.wesnoth.wail.ProtectUnitType#getProcType()
   * @see #getProtectUnitType()
   * @generated
   */
  EAttribute getProtectUnitType_ProcType();

  /**
   * Returns the meta object for class '{@link org.xtext.wesnoth.wail.ProtectLocation <em>Protect Location</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Protect Location</em>'.
   * @see org.xtext.wesnoth.wail.ProtectLocation
   * @generated
   */
  EClass getProtectLocation();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.wesnoth.wail.ProtectLocation#getXAxis <em>XAxis</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>XAxis</em>'.
   * @see org.xtext.wesnoth.wail.ProtectLocation#getXAxis()
   * @see #getProtectLocation()
   * @generated
   */
  EAttribute getProtectLocation_XAxis();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.wesnoth.wail.ProtectLocation#getYAxis <em>YAxis</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>YAxis</em>'.
   * @see org.xtext.wesnoth.wail.ProtectLocation#getYAxis()
   * @see #getProtectLocation()
   * @generated
   */
  EAttribute getProtectLocation_YAxis();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.wesnoth.wail.ProtectLocation#getLocValue <em>Loc Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Loc Value</em>'.
   * @see org.xtext.wesnoth.wail.ProtectLocation#getLocValue()
   * @see #getProtectLocation()
   * @generated
   */
  EAttribute getProtectLocation_LocValue();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.wesnoth.wail.ProtectLocation#getProcRad <em>Proc Rad</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Proc Rad</em>'.
   * @see org.xtext.wesnoth.wail.ProtectLocation#getProcRad()
   * @see #getProtectLocation()
   * @generated
   */
  EAttribute getProtectLocation_ProcRad();

  /**
   * Returns the meta object for class '{@link org.xtext.wesnoth.wail.GoaLocation <em>Goa Location</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Goa Location</em>'.
   * @see org.xtext.wesnoth.wail.GoaLocation
   * @generated
   */
  EClass getGoaLocation();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.wesnoth.wail.GoaLocation#getXAxis <em>XAxis</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>XAxis</em>'.
   * @see org.xtext.wesnoth.wail.GoaLocation#getXAxis()
   * @see #getGoaLocation()
   * @generated
   */
  EAttribute getGoaLocation_XAxis();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.wesnoth.wail.GoaLocation#getYAxis <em>YAxis</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>YAxis</em>'.
   * @see org.xtext.wesnoth.wail.GoaLocation#getYAxis()
   * @see #getGoaLocation()
   * @generated
   */
  EAttribute getGoaLocation_YAxis();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.wesnoth.wail.GoaLocation#getLocValue <em>Loc Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Loc Value</em>'.
   * @see org.xtext.wesnoth.wail.GoaLocation#getLocValue()
   * @see #getGoaLocation()
   * @generated
   */
  EAttribute getGoaLocation_LocValue();

  /**
   * Returns the meta object for class '{@link org.xtext.wesnoth.wail.Aggression <em>Aggression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Aggression</em>'.
   * @see org.xtext.wesnoth.wail.Aggression
   * @generated
   */
  EClass getAggression();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.wesnoth.wail.Aggression#getAggressionVal <em>Aggression Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Aggression Val</em>'.
   * @see org.xtext.wesnoth.wail.Aggression#getAggressionVal()
   * @see #getAggression()
   * @generated
   */
  EAttribute getAggression_AggressionVal();

  /**
   * Returns the meta object for class '{@link org.xtext.wesnoth.wail.Caution <em>Caution</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Caution</em>'.
   * @see org.xtext.wesnoth.wail.Caution
   * @generated
   */
  EClass getCaution();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.wesnoth.wail.Caution#getCautionval <em>Cautionval</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Cautionval</em>'.
   * @see org.xtext.wesnoth.wail.Caution#getCautionval()
   * @see #getCaution()
   * @generated
   */
  EAttribute getCaution_Cautionval();

  /**
   * Returns the meta object for class '{@link org.xtext.wesnoth.wail.Defualt_CA <em>Defualt CA</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Defualt CA</em>'.
   * @see org.xtext.wesnoth.wail.Defualt_CA
   * @generated
   */
  EClass getDefualt_CA();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.wesnoth.wail.Defualt_CA#getCaType <em>Ca Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ca Type</em>'.
   * @see org.xtext.wesnoth.wail.Defualt_CA#getCaType()
   * @see #getDefualt_CA()
   * @generated
   */
  EAttribute getDefualt_CA_CaType();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.wesnoth.wail.Defualt_CA#getCost <em>Cost</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Cost</em>'.
   * @see org.xtext.wesnoth.wail.Defualt_CA#getCost()
   * @see #getDefualt_CA()
   * @generated
   */
  EAttribute getDefualt_CA_Cost();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  WailFactory getWailFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.wesnoth.wail.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.wesnoth.wail.impl.ModelImpl
     * @see org.xtext.wesnoth.wail.impl.WailPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ELEMENTS = eINSTANCE.getModel_Elements();

    /**
     * The meta object literal for the '{@link org.xtext.wesnoth.wail.impl.RuleImpl <em>Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.wesnoth.wail.impl.RuleImpl
     * @see org.xtext.wesnoth.wail.impl.WailPackageImpl#getRule()
     * @generated
     */
    EClass RULE = eINSTANCE.getRule();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE__NAME = eINSTANCE.getRule_Name();

    /**
     * The meta object literal for the '<em><b>Fragments</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE__FRAGMENTS = eINSTANCE.getRule_Fragments();

    /**
     * The meta object literal for the '<em><b>Goals</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE__GOALS = eINSTANCE.getRule_Goals();

    /**
     * The meta object literal for the '<em><b>Aggressionval</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE__AGGRESSIONVAL = eINSTANCE.getRule_Aggressionval();

    /**
     * The meta object literal for the '<em><b>Cautionval</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE__CAUTIONVAL = eINSTANCE.getRule_Cautionval();

    /**
     * The meta object literal for the '<em><b>Grouping Val</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE__GROUPING_VAL = eINSTANCE.getRule_GroupingVal();

    /**
     * The meta object literal for the '<em><b>Units</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE__UNITS = eINSTANCE.getRule_Units();

    /**
     * The meta object literal for the '{@link org.xtext.wesnoth.wail.impl.GroupingImpl <em>Grouping</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.wesnoth.wail.impl.GroupingImpl
     * @see org.xtext.wesnoth.wail.impl.WailPackageImpl#getGrouping()
     * @generated
     */
    EClass GROUPING = eINSTANCE.getGrouping();

    /**
     * The meta object literal for the '<em><b>Grouping Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GROUPING__GROUPING_VAL = eINSTANCE.getGrouping_GroupingVal();

    /**
     * The meta object literal for the '{@link org.xtext.wesnoth.wail.impl.FragmentImpl <em>Fragment</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.wesnoth.wail.impl.FragmentImpl
     * @see org.xtext.wesnoth.wail.impl.WailPackageImpl#getFragment()
     * @generated
     */
    EClass FRAGMENT = eINSTANCE.getFragment();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FRAGMENT__CONDITION = eINSTANCE.getFragment_Condition();

    /**
     * The meta object literal for the '<em><b>Defualt cas</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FRAGMENT__DEFUALT_CAS = eINSTANCE.getFragment_Defualt_cas();

    /**
     * The meta object literal for the '{@link org.xtext.wesnoth.wail.impl.ConditionalImpl <em>Conditional</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.wesnoth.wail.impl.ConditionalImpl
     * @see org.xtext.wesnoth.wail.impl.WailPackageImpl#getConditional()
     * @generated
     */
    EClass CONDITIONAL = eINSTANCE.getConditional();

    /**
     * The meta object literal for the '<em><b>X</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITIONAL__X = eINSTANCE.getConditional_X();

    /**
     * The meta object literal for the '{@link org.xtext.wesnoth.wail.impl.RecruitmentImpl <em>Recruitment</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.wesnoth.wail.impl.RecruitmentImpl
     * @see org.xtext.wesnoth.wail.impl.WailPackageImpl#getRecruitment()
     * @generated
     */
    EClass RECRUITMENT = eINSTANCE.getRecruitment();

    /**
     * The meta object literal for the '<em><b>Unitslist</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RECRUITMENT__UNITSLIST = eINSTANCE.getRecruitment_Unitslist();

    /**
     * The meta object literal for the '<em><b>Turns</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RECRUITMENT__TURNS = eINSTANCE.getRecruitment_Turns();

    /**
     * The meta object literal for the '<em><b>Importance</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RECRUITMENT__IMPORTANCE = eINSTANCE.getRecruitment_Importance();

    /**
     * The meta object literal for the '<em><b>Number</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RECRUITMENT__NUMBER = eINSTANCE.getRecruitment_Number();

    /**
     * The meta object literal for the '{@link org.xtext.wesnoth.wail.impl.whenRulesImpl <em>when Rules</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.wesnoth.wail.impl.whenRulesImpl
     * @see org.xtext.wesnoth.wail.impl.WailPackageImpl#getwhenRules()
     * @generated
     */
    EClass WHEN_RULES = eINSTANCE.getwhenRules();

    /**
     * The meta object literal for the '{@link org.xtext.wesnoth.wail.impl.IDEqualsImpl <em>ID Equals</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.wesnoth.wail.impl.IDEqualsImpl
     * @see org.xtext.wesnoth.wail.impl.WailPackageImpl#getIDEquals()
     * @generated
     */
    EClass ID_EQUALS = eINSTANCE.getIDEquals();

    /**
     * The meta object literal for the '<em><b>Unit ID</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ID_EQUALS__UNIT_ID = eINSTANCE.getIDEquals_UnitID();

    /**
     * The meta object literal for the '{@link org.xtext.wesnoth.wail.impl.BaselineImpl <em>Baseline</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.wesnoth.wail.impl.BaselineImpl
     * @see org.xtext.wesnoth.wail.impl.WailPackageImpl#getBaseline()
     * @generated
     */
    EClass BASELINE = eINSTANCE.getBaseline();

    /**
     * The meta object literal for the '<em><b>Always</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BASELINE__ALWAYS = eINSTANCE.getBaseline_Always();

    /**
     * The meta object literal for the '{@link org.xtext.wesnoth.wail.impl.DamageImpl <em>Damage</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.wesnoth.wail.impl.DamageImpl
     * @see org.xtext.wesnoth.wail.impl.WailPackageImpl#getDamage()
     * @generated
     */
    EClass DAMAGE = eINSTANCE.getDamage();

    /**
     * The meta object literal for the '<em><b>Health</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DAMAGE__HEALTH = eINSTANCE.getDamage_Health();

    /**
     * The meta object literal for the '{@link org.xtext.wesnoth.wail.impl.AtLocationImpl <em>At Location</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.wesnoth.wail.impl.AtLocationImpl
     * @see org.xtext.wesnoth.wail.impl.WailPackageImpl#getAtLocation()
     * @generated
     */
    EClass AT_LOCATION = eINSTANCE.getAtLocation();

    /**
     * The meta object literal for the '<em><b>XAxis</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AT_LOCATION__XAXIS = eINSTANCE.getAtLocation_XAxis();

    /**
     * The meta object literal for the '<em><b>YAxis</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AT_LOCATION__YAXIS = eINSTANCE.getAtLocation_YAxis();

    /**
     * The meta object literal for the '{@link org.xtext.wesnoth.wail.impl.UnitEqualsImpl <em>Unit Equals</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.wesnoth.wail.impl.UnitEqualsImpl
     * @see org.xtext.wesnoth.wail.impl.WailPackageImpl#getUnitEquals()
     * @generated
     */
    EClass UNIT_EQUALS = eINSTANCE.getUnitEquals();

    /**
     * The meta object literal for the '<em><b>Unit</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNIT_EQUALS__UNIT = eINSTANCE.getUnitEquals_Unit();

    /**
     * The meta object literal for the '{@link org.xtext.wesnoth.wail.impl.GoalImpl <em>Goal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.wesnoth.wail.impl.GoalImpl
     * @see org.xtext.wesnoth.wail.impl.WailPackageImpl#getGoal()
     * @generated
     */
    EClass GOAL = eINSTANCE.getGoal();

    /**
     * The meta object literal for the '<em><b>Goal</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GOAL__GOAL = eINSTANCE.getGoal_Goal();

    /**
     * The meta object literal for the '{@link org.xtext.wesnoth.wail.impl.ProtectLeaderImpl <em>Protect Leader</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.wesnoth.wail.impl.ProtectLeaderImpl
     * @see org.xtext.wesnoth.wail.impl.WailPackageImpl#getProtectLeader()
     * @generated
     */
    EClass PROTECT_LEADER = eINSTANCE.getProtectLeader();

    /**
     * The meta object literal for the '<em><b>Location Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROTECT_LEADER__LOCATION_VALUE = eINSTANCE.getProtectLeader_LocationValue();

    /**
     * The meta object literal for the '<em><b>Protection Radius</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROTECT_LEADER__PROTECTION_RADIUS = eINSTANCE.getProtectLeader_ProtectionRadius();

    /**
     * The meta object literal for the '<em><b>Proc Side</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROTECT_LEADER__PROC_SIDE = eINSTANCE.getProtectLeader_ProcSide();

    /**
     * The meta object literal for the '{@link org.xtext.wesnoth.wail.impl.ProtectUnitIDImpl <em>Protect Unit ID</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.wesnoth.wail.impl.ProtectUnitIDImpl
     * @see org.xtext.wesnoth.wail.impl.WailPackageImpl#getProtectUnitID()
     * @generated
     */
    EClass PROTECT_UNIT_ID = eINSTANCE.getProtectUnitID();

    /**
     * The meta object literal for the '<em><b>Location Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROTECT_UNIT_ID__LOCATION_VALUE = eINSTANCE.getProtectUnitID_LocationValue();

    /**
     * The meta object literal for the '<em><b>Protection Radius</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROTECT_UNIT_ID__PROTECTION_RADIUS = eINSTANCE.getProtectUnitID_ProtectionRadius();

    /**
     * The meta object literal for the '<em><b>Proc Side</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROTECT_UNIT_ID__PROC_SIDE = eINSTANCE.getProtectUnitID_ProcSide();

    /**
     * The meta object literal for the '<em><b>Proc ID</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROTECT_UNIT_ID__PROC_ID = eINSTANCE.getProtectUnitID_ProcID();

    /**
     * The meta object literal for the '{@link org.xtext.wesnoth.wail.impl.ProtectUnitTypeImpl <em>Protect Unit Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.wesnoth.wail.impl.ProtectUnitTypeImpl
     * @see org.xtext.wesnoth.wail.impl.WailPackageImpl#getProtectUnitType()
     * @generated
     */
    EClass PROTECT_UNIT_TYPE = eINSTANCE.getProtectUnitType();

    /**
     * The meta object literal for the '<em><b>Location Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROTECT_UNIT_TYPE__LOCATION_VALUE = eINSTANCE.getProtectUnitType_LocationValue();

    /**
     * The meta object literal for the '<em><b>Protection Radius</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROTECT_UNIT_TYPE__PROTECTION_RADIUS = eINSTANCE.getProtectUnitType_ProtectionRadius();

    /**
     * The meta object literal for the '<em><b>Proc Side</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROTECT_UNIT_TYPE__PROC_SIDE = eINSTANCE.getProtectUnitType_ProcSide();

    /**
     * The meta object literal for the '<em><b>Proc Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROTECT_UNIT_TYPE__PROC_TYPE = eINSTANCE.getProtectUnitType_ProcType();

    /**
     * The meta object literal for the '{@link org.xtext.wesnoth.wail.impl.ProtectLocationImpl <em>Protect Location</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.wesnoth.wail.impl.ProtectLocationImpl
     * @see org.xtext.wesnoth.wail.impl.WailPackageImpl#getProtectLocation()
     * @generated
     */
    EClass PROTECT_LOCATION = eINSTANCE.getProtectLocation();

    /**
     * The meta object literal for the '<em><b>XAxis</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROTECT_LOCATION__XAXIS = eINSTANCE.getProtectLocation_XAxis();

    /**
     * The meta object literal for the '<em><b>YAxis</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROTECT_LOCATION__YAXIS = eINSTANCE.getProtectLocation_YAxis();

    /**
     * The meta object literal for the '<em><b>Loc Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROTECT_LOCATION__LOC_VALUE = eINSTANCE.getProtectLocation_LocValue();

    /**
     * The meta object literal for the '<em><b>Proc Rad</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROTECT_LOCATION__PROC_RAD = eINSTANCE.getProtectLocation_ProcRad();

    /**
     * The meta object literal for the '{@link org.xtext.wesnoth.wail.impl.GoaLocationImpl <em>Goa Location</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.wesnoth.wail.impl.GoaLocationImpl
     * @see org.xtext.wesnoth.wail.impl.WailPackageImpl#getGoaLocation()
     * @generated
     */
    EClass GOA_LOCATION = eINSTANCE.getGoaLocation();

    /**
     * The meta object literal for the '<em><b>XAxis</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GOA_LOCATION__XAXIS = eINSTANCE.getGoaLocation_XAxis();

    /**
     * The meta object literal for the '<em><b>YAxis</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GOA_LOCATION__YAXIS = eINSTANCE.getGoaLocation_YAxis();

    /**
     * The meta object literal for the '<em><b>Loc Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GOA_LOCATION__LOC_VALUE = eINSTANCE.getGoaLocation_LocValue();

    /**
     * The meta object literal for the '{@link org.xtext.wesnoth.wail.impl.AggressionImpl <em>Aggression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.wesnoth.wail.impl.AggressionImpl
     * @see org.xtext.wesnoth.wail.impl.WailPackageImpl#getAggression()
     * @generated
     */
    EClass AGGRESSION = eINSTANCE.getAggression();

    /**
     * The meta object literal for the '<em><b>Aggression Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AGGRESSION__AGGRESSION_VAL = eINSTANCE.getAggression_AggressionVal();

    /**
     * The meta object literal for the '{@link org.xtext.wesnoth.wail.impl.CautionImpl <em>Caution</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.wesnoth.wail.impl.CautionImpl
     * @see org.xtext.wesnoth.wail.impl.WailPackageImpl#getCaution()
     * @generated
     */
    EClass CAUTION = eINSTANCE.getCaution();

    /**
     * The meta object literal for the '<em><b>Cautionval</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CAUTION__CAUTIONVAL = eINSTANCE.getCaution_Cautionval();

    /**
     * The meta object literal for the '{@link org.xtext.wesnoth.wail.impl.Defualt_CAImpl <em>Defualt CA</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.wesnoth.wail.impl.Defualt_CAImpl
     * @see org.xtext.wesnoth.wail.impl.WailPackageImpl#getDefualt_CA()
     * @generated
     */
    EClass DEFUALT_CA = eINSTANCE.getDefualt_CA();

    /**
     * The meta object literal for the '<em><b>Ca Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEFUALT_CA__CA_TYPE = eINSTANCE.getDefualt_CA_CaType();

    /**
     * The meta object literal for the '<em><b>Cost</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEFUALT_CA__COST = eINSTANCE.getDefualt_CA_Cost();

  }

} //WailPackage
