/*
 * generated by Xtext 2.22.0
 */
package org.xtext.wesnoth.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class WailAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/wesnoth/parser/antlr/internal/InternalWail.tokens");
	}
}
