/*
 * generated by Xtext 2.22.0
 */
package org.xtext.wesnoth.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.wesnoth.parser.antlr.internal.InternalWailParser;
import org.xtext.wesnoth.services.WailGrammarAccess;

public class WailParser extends AbstractAntlrParser {

	@Inject
	private WailGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalWailParser createParser(XtextTokenStream stream) {
		return new InternalWailParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public WailGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(WailGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
