/*
 * generated by Xtext 2.22.0
 */
package org.xtext.wesnoth.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.wesnoth.wail.ui.internal.WailActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class WailExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(WailActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		WailActivator activator = WailActivator.getInstance();
		return activator != null ? activator.getInjector(WailActivator.ORG_XTEXT_WESNOTH_WAIL) : null;
	}

}
