/*
 * generated by Xtext 2.22.0
 */
package org.xtext.wesnoth.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class WailUiModule extends AbstractWailUiModule {

	public WailUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
