/**
 * generated by Xtext 2.22.0
 */
package org.xtext.wesnoth.wail.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.wesnoth.wail.ProtectLeader;
import org.xtext.wesnoth.wail.WailPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Protect Leader</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.wesnoth.wail.impl.ProtectLeaderImpl#getLocationValue <em>Location Value</em>}</li>
 *   <li>{@link org.xtext.wesnoth.wail.impl.ProtectLeaderImpl#getProtectionRadius <em>Protection Radius</em>}</li>
 *   <li>{@link org.xtext.wesnoth.wail.impl.ProtectLeaderImpl#getProcSide <em>Proc Side</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ProtectLeaderImpl extends GoalImpl implements ProtectLeader
{
  /**
   * The default value of the '{@link #getLocationValue() <em>Location Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLocationValue()
   * @generated
   * @ordered
   */
  protected static final int LOCATION_VALUE_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getLocationValue() <em>Location Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLocationValue()
   * @generated
   * @ordered
   */
  protected int locationValue = LOCATION_VALUE_EDEFAULT;

  /**
   * The default value of the '{@link #getProtectionRadius() <em>Protection Radius</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProtectionRadius()
   * @generated
   * @ordered
   */
  protected static final int PROTECTION_RADIUS_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getProtectionRadius() <em>Protection Radius</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProtectionRadius()
   * @generated
   * @ordered
   */
  protected int protectionRadius = PROTECTION_RADIUS_EDEFAULT;

  /**
   * The default value of the '{@link #getProcSide() <em>Proc Side</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProcSide()
   * @generated
   * @ordered
   */
  protected static final int PROC_SIDE_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getProcSide() <em>Proc Side</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProcSide()
   * @generated
   * @ordered
   */
  protected int procSide = PROC_SIDE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ProtectLeaderImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return WailPackage.Literals.PROTECT_LEADER;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getLocationValue()
  {
    return locationValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLocationValue(int newLocationValue)
  {
    int oldLocationValue = locationValue;
    locationValue = newLocationValue;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, WailPackage.PROTECT_LEADER__LOCATION_VALUE, oldLocationValue, locationValue));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getProtectionRadius()
  {
    return protectionRadius;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setProtectionRadius(int newProtectionRadius)
  {
    int oldProtectionRadius = protectionRadius;
    protectionRadius = newProtectionRadius;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, WailPackage.PROTECT_LEADER__PROTECTION_RADIUS, oldProtectionRadius, protectionRadius));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getProcSide()
  {
    return procSide;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setProcSide(int newProcSide)
  {
    int oldProcSide = procSide;
    procSide = newProcSide;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, WailPackage.PROTECT_LEADER__PROC_SIDE, oldProcSide, procSide));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case WailPackage.PROTECT_LEADER__LOCATION_VALUE:
        return getLocationValue();
      case WailPackage.PROTECT_LEADER__PROTECTION_RADIUS:
        return getProtectionRadius();
      case WailPackage.PROTECT_LEADER__PROC_SIDE:
        return getProcSide();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case WailPackage.PROTECT_LEADER__LOCATION_VALUE:
        setLocationValue((Integer)newValue);
        return;
      case WailPackage.PROTECT_LEADER__PROTECTION_RADIUS:
        setProtectionRadius((Integer)newValue);
        return;
      case WailPackage.PROTECT_LEADER__PROC_SIDE:
        setProcSide((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case WailPackage.PROTECT_LEADER__LOCATION_VALUE:
        setLocationValue(LOCATION_VALUE_EDEFAULT);
        return;
      case WailPackage.PROTECT_LEADER__PROTECTION_RADIUS:
        setProtectionRadius(PROTECTION_RADIUS_EDEFAULT);
        return;
      case WailPackage.PROTECT_LEADER__PROC_SIDE:
        setProcSide(PROC_SIDE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case WailPackage.PROTECT_LEADER__LOCATION_VALUE:
        return locationValue != LOCATION_VALUE_EDEFAULT;
      case WailPackage.PROTECT_LEADER__PROTECTION_RADIUS:
        return protectionRadius != PROTECTION_RADIUS_EDEFAULT;
      case WailPackage.PROTECT_LEADER__PROC_SIDE:
        return procSide != PROC_SIDE_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (locationValue: ");
    result.append(locationValue);
    result.append(", protectionRadius: ");
    result.append(protectionRadius);
    result.append(", procSide: ");
    result.append(procSide);
    result.append(')');
    return result.toString();
  }

} //ProtectLeaderImpl
