/**
 * generated by Xtext 2.22.0
 */
package org.xtext.wesnoth.wail.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.wesnoth.wail.WailPackage;
import org.xtext.wesnoth.wail.whenRules;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>when Rules</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class whenRulesImpl extends MinimalEObjectImpl.Container implements whenRules
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected whenRulesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return WailPackage.Literals.WHEN_RULES;
  }

} //whenRulesImpl
